# Generated by Django 6.0.5 on 2026-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_alter_persona_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tortuga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('velocidad', models.IntegerField()),
                ('fuerza', models.IntegerField()),
            ],
        ),
    ]
