# Generated by Django 6.0.5 on 2026-06-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0003_tortuga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pokemon', models.CharField(max_length=50)),
                ('num_pokedex', models.IntegerField()),
                ('tipo1', models.CharField(max_length=50)),
                ('tipo2', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defensa', models.IntegerField()),
            ],
        ),
    ]
