# Generated by Django 6.0.6 on 2026-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0005_chiste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
    ]
